<AddTransactionScreen>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: get_color_from_hex(Colors.BACKGROUND)

            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: '64dp'
            padding: '16dp', 0
            spacing: '8dp'
            canvas.before:
                Color:
                    rgba: get_color_from_hex(Colors.BRAND_PRIMARY)

                Rectangle:
                    pos: self.pos
                    size: self.size
                    
            MDIconButton:
                icon: 'arrow-left'
                on_release: root.go_to_dashboard()
                theme_icon_color: 'Custom'
                icon_color: get_color_from_hex(Colors.TEXT_ON_PRIMARY)
                pos_hint: {'center_y': .5}

            MDLabel:
                text: 'Add Transaction'
                font_size: '26sp'
                size_hint_x: 1
                theme_text_color: 'Custom'
                text_color: get_color_from_hex(Colors.TEXT_ON_PRIMARY)

            MDIconButton:
                icon: 'content-save'
                on_release: root.save_transaction()
                theme_icon_color: 'Custom'
                icon_color: get_color_from_hex(Colors.TEXT_ON_PRIMARY)
                pos_hint: {'center_y': .5}

        Widget:
            size_hint_y: None
            height: "1dp"

            canvas.before:
                Color:
                    rgba: get_color_from_hex(Colors.BORDER)

                Rectangle:
                    pos: self.pos
                    size: self.size        

        ScrollView:

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                padding: 20
                spacing: 15

                BoxLayout:
                    size_hint_y: None
                    height: '56dp'
                    padding: '10dp'

                    orientation: 'horizontal'
                    spacing: '10dp'

                    EnkryonFilterButton:
                        id: income_button
                        text: "INCOME"
                        size_hint_x: 1
                        on_release: root.update_groups_button('income')

                    EnkryonFilterButton:
                        id: expense_button
                        text: "EXPENSE"
                        size_hint_x: 1
                        on_release: root.update_groups_button('expense')
                        
                OutlinedCard:
                    size_hint_y: None
                    height: "180dp"
                    orientation: "horizontal"
                    padding: "10dp"

                    AnchorLayout:
                        anchor_x: "center"
                        anchor_y: "top"
                        size_hint_x: 0.4

                        EnkryonPrimaryButton:
                            id: account_selector
                            text: 'Select Account'
                            size_hint: 1, None
                            on_release: root.open_account_menu()

                    MDLabel:
                        id: amount_label
                        halign: "right"
                        valign: "middle"
                        text_size: self.size
                        font_size: "32sp"
                        text: "₱ 0"

                GridLayout:
                    id: keypad_container
                    cols: 4
                    spacing: "8dp"
                    size_hint_y: None
                    height: self.minimum_height

                OutlinedCard:
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    padding: '20dp'
                    spacing: '20dp'

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: '64dp'
                        spacing: '20dp'

                        OutlinedCard:
                            id: group_selector
                            size_hint: 1, None
                            height: "64dp"
                            ripple_behavior: True
                            md_bg_color: get_color_from_hex(Colors.BRAND_ACCENT_SOFT)
                            on_release: root.open_groups_menu()

                            MDLabel:
                                id: group_label
                                halign: "center"
                                theme_text_color: "Custom"
                                text_color: get_color_from_hex(Colors.BRAND_PRIMARY)

                        OutlinedCard:
                            id: category_selector
                            size_hint: 1, None
                            height: "64dp"
                            ripple_behavior: True
                            md_bg_color: get_color_from_hex(Colors.BRAND_ACCENT_SOFT)
                            on_release: root.open_categories_menu()

                            MDLabel:
                                id: category_label
                                halign: "center"
                                theme_text_color: "Custom"
                                text_color: get_color_from_hex(Colors.BRAND_PRIMARY)

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: '64dp'
                        spacing: '20dp'

                        OutlinedCard:
                            id: date_selector
                            size_hint: 1, None
                            height: "64dp"
                            ripple_behavior: True
                            md_bg_color: get_color_from_hex(Colors.BRAND_ACCENT_SOFT)
                            on_release: root.open_date_picker()

                            MDLabel:
                                id: date_label
                                halign: "center"
                                theme_text_color: "Custom"
                                text_color: get_color_from_hex(Colors.BRAND_PRIMARY)

                        OutlinedCard:
                            id: time_selector
                            size_hint: 1, None
                            height: "64dp"
                            ripple_behavior: True
                            md_bg_color: get_color_from_hex(Colors.BRAND_ACCENT_SOFT)
                            on_release: root.open_time_picker()

                            MDLabel:
                                id: time_label
                                halign: "center"
                                theme_text_color: "Custom"
                                text_color: get_color_from_hex(Colors.BRAND_PRIMARY)

                OutlinedCard:
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    padding: dp(16)

                    MDLabel:
                        text: 'Notes'
                        size_hint_y: None
                        height: dp(20)

                    MDCard:
                        size_hint_y: None
                        height: dp(56)
                        ripple_behavior: True
                        on_release: root.add_notes()
                        padding: dp(16)

                        MDLabel:
                            id: notes_label
                            text: 'Add notes'
                            halign: 'left'
                            valign: 'middle'
                            text_size: self.size
                            theme_text_color: 'Hint'
                            shorten: True
                            shorten_from: 'right'