<AddTransactionScreen>:
    ScrollView:
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            padding: 20
            spacing: 15

            MDCard:
                size_hint_y: None
                height: 50

                BoxLayout:
                    orientation: 'horizontal'

                    MDLabel:
                        text: 'Header'

                    MDIconButton:
                        icon: 'close'
                        on_release:
                            root.go_to_dashboard()

                    MDIconButton:
                        icon: 'content-save'
                        on_release:
                            root.save_transaction()

            MDCard:
                size_hint_y: None
                height: 50

                ToggleButton:
                    id: income_button
                    text: 'INCOME'
                    group: 'transaction_type'
                    on_release:
                        root.update_groups_button()

                ToggleButton:
                    id: expense_button
                    text: 'EXPENSE'
                    group: 'transaction_type'
                    on_release:
                        root.update_groups_button()
                    
            MDCard:
                size_hint_y: None
                height: 350
                orientation: 'vertical'

                BoxLayout:

                    MDFillRoundFlatButton:
                        id: account_button
                        on_release:
                            root.open_account_menu()

                    MDLabel:
                        size_hint_y: None
                        height: 150
                        id: amount_label
                        text: '₱ 0'

                GridLayout:
                    cols: 4
                    rows: 4
                    size_hint_y: None
                    height: 200

                    MDRaisedButton:
                        text: '7'
                        size_hint: (1, 1)
                        on_release:
                            root.press_number('7')

                    MDRaisedButton:
                        text: '8'
                        size_hint: (1, 1)
                        on_release:
                            root.press_number('8')
                
                    MDRaisedButton:
                        text: '9'
                        size_hint: (1, 1)
                        on_release:
                            root.press_number('9')

                    MDRaisedButton:
                        text: 'delete'
                        size_hint: (1, 1)
                        on_release:
                            root.delete_last()

                    MDRaisedButton:
                        text: '4'
                        size_hint: (1, 1)
                        on_release:
                            root.press_number('4')

                    MDRaisedButton:
                        text: '5'
                        size_hint: (1, 1)
                        on_release:
                            root.press_number('5')
                
                    MDRaisedButton:
                        text: '6'
                        size_hint: (1, 1)
                        on_release:
                            root.press_number('6')

                    MDRaisedButton:
                        text: 'clear'
                        size_hint: (1, 1)
                        on_release:
                            root.clear()

                    MDRaisedButton:
                        text: '1'
                        size_hint: (1, 1)
                        on_release:
                            root.press_number('1')

                    MDRaisedButton:
                        text: '2'
                        size_hint: (1, 1)
                        on_release:
                            root.press_number('2')
                
                    MDRaisedButton:
                        text: '3'
                        size_hint: (1, 1)
                        on_release:
                            root.press_number('3')

                    MDRaisedButton:
                        text: '.'
                        size_hint: (1, 1)
                        on_release:
                            root.add_decimal()

                    MDLabel:
                        
                    MDRaisedButton:
                        text: '0'
                        size_hint: (1, 1)
                        on_release:
                            root.press_number('0')

            MDCard:
                orientation: 'vertical'
                size_hint_y: None
                height: 100

                GridLayout:
                    cols: 2
                    rows: 2
                    size_hint_y: None
                    height: 100

                    MDFillRoundFlatButton:
                        id: groups_button
                        on_release:
                            root.open_groups_menu()

                    MDFillRoundFlatButton:
                        id: categories_button
                        on_release:
                            root.open_categories_menu()

                    MDFillRoundFlatIconButton:
                        id: date_button
                        icon: 'calendar'
                        on_release:
                            root.open_date_picker()

                    MDFillRoundFlatIconButton:
                        id: time_button
                        icon: 'clock-outline'
                        on_release:
                            root.open_time_picker()

            MDCard:
                size_hint_y: None
                height: 200

                MDTextField:
                    id: notes_input
                    multiline: True