<CategoryCard>
    size_hint_y: None
    height: category_content.height

    canvas.after:
        Color:
            rgba: get_color_from_hex(Colors.BRAND_PRIMARY)

        Line:
            rounded_rectangle:
                (self.x, self.y,
                self.width, self.height,
                self.radius[0])
            width: 1.2

    BoxLayout:
        id: category_content
        orientation: 'vertical'
        size_hint_y: None
        height: self.minimum_height

        BoxLayout:
            size_hint_y: None
            height: self.minimum_height

            Widget:
                size_hint_x: None
                width: 20

            MDLabel:
                id: category_name

            MDIconButton:
                icon: 'pencil'
                on_release:
                    root.edit_category()

            MDIconButton:
                icon: 'delete'
                on_release:
                    root.delete_category()

<CategoryGroupCard>
    size_hint_y: None
    height: self.minimum_height

    canvas.after:
        Color:
            rgba: get_color_from_hex(Colors.BRAND_PRIMARY)

        Line:
            rounded_rectangle:
                (self.x, self.y,
                self.width, self.height,
                self.radius[0])
            width: 1.2

    BoxLayout:
        id: group_content
        orientation: 'vertical'
        size_hint_y: None
        height: self.minimum_height 

        BoxLayout:
            size_hint_y: None
            height: '56dp'
            padding: '10dp', 0
            spacing: '10dp'

            MDLabel:
                id: group_name
                text_size: self.size
                valign: 'middle'

            MDIconButton:
                icon: "plus"
                on_release:
                    root.add_category()

            MDIconButton:
                icon: "pencil"
                on_release:
                    root.edit_group()

            MDIconButton:
                icon: "delete"
                on_release:
                    root.delete_group()

            MDIconButton:
                id: toggle_button
                icon: "chevron-down"
                on_release:
                    root.toggle_group()

        BoxLayout:
            id: categories_container
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            padding: '10dp'
            spacing: '10dp'
            
<CategoriesScreen>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: get_color_from_hex(Colors.SURFACE_MUTED)

            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: '64dp'
            padding: '16dp', 0
            spacing: '8dp'
            canvas.before:
                Color:
                    rgba: get_color_from_hex(Colors.SURFACE_MUTED)

                Rectangle:
                    pos: self.pos
                    size: self.size
                    
            MDIconButton:
                icon: 'arrow-left'
                on_release: root.go_to_dashboard()
                theme_icon_color: 'Custom'
                icon_color: get_color_from_hex(Colors.BRAND_PRIMARY)
                pos_hint: {'center_y': .5}

            MDLabel:
                text: 'Categories'
                font_size: '26sp'
                size_hint_x: 1
                theme_text_color: 'Custom'
                text_color: get_color_from_hex(Colors.BRAND_PRIMARY)

        Widget:
            size_hint_y: None
            height: "1dp"

            canvas.before:
                Color:
                    rgba: get_color_from_hex(Colors.BORDER)

                Rectangle:
                    pos: self.pos
                    size: self.size        

        BoxLayout:
            size_hint_y: None
            height: '56dp'
            padding: '10dp'

            orientation: 'horizontal'
            spacing: '10dp'

            EnkryonFilterButton:
                id: income_button
                text: "INCOME"
                on_release: root.set_transaction_type('income')

            EnkryonFilterButton:
                id: expense_button
                text: "EXPENSE"
                on_release: root.set_transaction_type('expense')

        FloatLayout:
            
            ScrollView:
                size_hint_y: 1
                
                BoxLayout:
                    id: groups_container
                    size_hint_y: None
                    height: self.minimum_height
                    orientation: 'vertical'
                    padding: '10dp'
                    spacing: '10dp'

            MDCard:
                size_hint: None, None
                size: dp(42), dp(42)
                radius: [36]
                md_bg_color: get_color_from_hex(Colors.SURFACE_MUTED)

                pos_hint: {'right': .96, 'y': .03}

                on_release: root.add_group()

                AnchorLayout:

                    MDIcon:
                        icon: 'plus'
                        pos_hint: {'center_x': .5, 'center_y': .5}