<DashboardScreen>:
    ScrollView:
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            padding: 20
            spacing: 15

            MDCard:
                size_hint_y: None
                height: 50

                BoxLayout:
                    orientation: 'horizontal'
                        
                    MDLabel:
                        text: 'Header'

                    MDIconButton:
                        icon: 'cog'
                        on_release:
                            root.go_to_settings()

            MDCard:
                size_hint_y: None
                height: 200

                BoxLayout:
                    orientation: 'horizontal'

                    MDLabel:
                        text: 'Message'

                    BoxLayout:
                        orientation: 'vertical'

                        GridLayout:
                            size_hint_y: None
                            height: 50
                            cols: 2
                                
                            MDFillRoundFlatIconButton:
                                id: account_button
                                on_release:
                                    root.open_account_menu()

                            MDIconButton:
                                id: eye_button
                                on_release:
                                    root.toggle_balance()

                        MDLabel:
                            text: 'Current Balance'
                        
                        MDLabel:
                            id: balance_label
            
            GridLayout:
                size_hint_y: None
                height: 50
                cols: 3
                    
                MDFillRoundFlatIconButton:
                    icon: 'plus'
                    text: 'Add Transaction'
                    on_release:
                        root.go_to_add_transaction()

                MDFillRoundFlatIconButton:
                    icon: 'plus'
                    text: 'Add/Edit Account'
                    on_release:
                        root.go_to_accounts()

                MDFillRoundFlatIconButton:
                    icon: 'plus'
                    text: 'Add/Edit Category'
                    on_release:
                        root.go_to_categories()
                    
            GridLayout:
                size_hint_y: None
                height: 150

                cols: 2
                rows: 2

                MDCard:
                    size_hint_y: None
                    height: 50

                    orientation: 'vertical'
                    padding: 10

                    MDLabel:
                        text: 'Income:'

                MDCard:
                    size_hint_y: None
                    height: 50

                    orientation: 'vertical'
                    padding: 10

                    MDLabel:
                        text: 'Expenses:'
                
                MDFlatButton:
                    id: income_label

                MDFlatButton:
                    id: expense_label

            MDCard:
                size_hint_y: None
                height: 500

                orientation: 'vertical'
                padding: 10

                MDRaisedButton:
                    size_hint_y: None
                    height: 50

                    text: 'Transactions'
                    on_release:
                        root.go_to_transactions()

                GridLayout:
                    size_hint_y: None
                    height: 50

                    cols: 3

                    MDFlatButton:
                        text: 'All'

                    MDFlatButton:
                        text: 'Income'

                    MDFlatButton:
                        text: 'Expenses'

                ScrollView:

                    BoxLayout:
                        id: transactions_container
                        size_hint_y:None
                        height: self.minimum_height
                        orientation: 'vertical'