#:import dp kivy.metrics.dp

<CalendarTextButton@MDCard>

    size_hint: None, None
    size: dp(80), dp(40)

    radius: [20]
    ripple_behavior: True

    MDLabel:
        id: label
        halign: "center"
        valign: "middle"
        
<CalendarArrow@MDCard>

    size_hint: None, None
    size: dp(40), dp(40)

    radius: [20]
    ripple_behavior: True

    MDIcon:
        id: icon
        icon: ""
        halign: "center"
        valign: "middle"

<CalendarDay@MDCard>

    size_hint_y: None
    height: dp(45)

    radius: [22]
    ripple_behavior: True

    MDLabel:
        id: label
        halign: "center"
        valign: "middle"
    
<DatePickerDialog>

    size_hint: .9,.65
    auto_dismiss: False

    MDCard:
        orientation: "vertical"
        radius: [20]
        padding: dp(15)
        spacing: dp(15)

        MDBoxLayout:

            adaptive_height: True
            spacing: dp(10)
            CalendarArrow:
                id: previous

            MDLabel:
                id: month_label
                halign: "center"
                bold: True

            CalendarArrow:
                id: next

        MDGridLayout:
            cols: 7
            adaptive_height: True
            spacing: dp(5)
            id: weekday_grid

        MDGridLayout:

            cols: 7

            spacing: dp(5)

            id: calendar_grid

        MDBoxLayout:

            adaptive_height: True
            spacing: dp(10)

            Widget:

            CalendarArrow:
                id: cancel

                MDLabel:
                    text: "Cancel"
                    halign: "center"

            CalendarArrow:
                id: ok

                MDLabel:
                    text: "OK"
                    halign: "center"


<TimeValue@MDCard>

    size_hint: None, None
    size: dp(80), dp(100)

    radius: [20]
    ripple_behavior: False

    MDBoxLayout:
        orientation: "vertical"

        CalendarArrow:
            id: up

        MDLabel:
            id: value
            halign: "center"
            bold: True

        CalendarArrow:
            id: down

<TimePickerDialog>

    size_hint: .8, .45
    auto_dismiss: False

    MDCard:
        orientation: "vertical"
        padding: dp(15)
        spacing: dp(15)

        MDLabel:
            text: "Select Time"
            halign: "center"
            bold: True

        MDBoxLayout:

            adaptive_height: True
            spacing: dp(15)

            TimeValue:
                id: hour

            MDLabel:
                text: ":"
                adaptive_width: True
                halign: "center"

            TimeValue:
                id: minute

            TimeValue:
                id: ampm

        MDBoxLayout:

            adaptive_height: True

            CalendarTextButton:
                id: cancel


            CalendarTextButton:
                id: ok
