#:import dp kivy.metrics.dp

<CalendarDay>

    size_hint: None, None
    size: dp(32), dp(32)

    halign: 'center'
    valign: 'middle'
    text_size: self.size

    on_release:
        if self.day: self.picker.select_day(self)

    canvas.before:
        Color:
            rgba: get_color_from_hex(Colors.BRAND_ACCENT_SOFT) if root.selected else (0, 0, 0, 0)

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [16]
    
<DatePickerDialog>

    size_hint: .9, None
    height: dp(430)
    auto_dismiss: False

    MDCard:
        orientation: 'vertical'
        size_hint_y: None
        height: self.minimum_height
        radius: [16]

        MDCard:
            size_hint_y: None
            height: self.minimum_height
            spacing: dp(10)
            md_bg_color: get_color_from_hex(Colors.BRAND_PRIMARY_LIGHT)
            radius: [16, 16, 0, 0]


            MDCard:
                size_hint: None, None
                size: dp(64), dp(64)
                md_bg_color: (0, 0, 0, 0)
                on_release: root.previous_month()

                AnchorLayout:
                    
                    MDIcon:
                        icon: 'chevron-left'
                        theme_icon_color: 'Custom'
                        icon_color: get_color_from_hex(Colors.TEXT_ON_PRIMARY)
                        pos_hint: {'center_x': .5, 'center_y': .5}

            MDCard:
                md_bg_color: (0, 0, 0, 0)
                on_release:
                    pass

                MDLabel:
                    id: month_label
                    theme_text_color: 'Custom'
                    text_color: get_color_from_hex(Colors.TEXT_ON_PRIMARY)
                    halign: 'center'
                    bold: True

            MDCard:
                size_hint: None, None
                size: dp(64), dp(64)
                md_bg_color: (0, 0, 0, 0)
                on_release: root.next_month()

                AnchorLayout:

                    MDIcon:
                        icon: 'chevron-right'
                        theme_icon_color: 'Custom'
                        icon_color: get_color_from_hex(Colors.TEXT_ON_PRIMARY)
                        pos_hint: {'center_x': .5, 'center_y': .5}

        MDCard:
            orientation: 'vertical'
            size_hint_y: None
            height: dp(330)

            radius: [20]
            padding: [32, 16, 32, 16]
            spacing: dp(15)

            BoxLayout:
                size_hint_y: None
                height: dp(32)

                AnchorLayout:

                    GridLayout:
                        id: weekday_grid
                        cols: 7
                        size_hint: None, None
                        width: self.minimum_width
                        height: self.minimum_height
                        spacing: dp(10)

            Widget:
                size_hint_y: None
                height: "1dp"

                canvas.before:
                    Color:
                        rgba: get_color_from_hex(Colors.BORDER)

                    Rectangle:
                        pos: self.pos
                        size: self.size       

            BoxLayout:
                size_hint_y: None
                height: dp(242)
                
                AnchorLayout:

                    GridLayout:
                        id: calendar_grid
                        cols: 7
                        size_hint: None, None
                        width: self.minimum_width
                        height: dp(242)
                        spacing: dp(10)

        MDCard:
            adaptive_height: True
            padding: [50, 0, 0, 0]

            MDCard:
                on_release:
                    root.dismiss()

                MDLabel:
                    text: "Cancel"
                    halign: "left"

<TimeScroll@MDLabel>
    text_size: self.size
    halign: 'center'
    valign: 'middle'
    font_style: 'H5'

<TimePickerDialog>

    size_hint: .6, .30
    auto_dismiss: False

    MDCard:
        orientation: 'vertical'

        FloatLayout:

            MDCard:
                size_hint: 0.9, None
                height: dp(40)
                pos_hint: {'center_x': .5, 'center_y': .5}
                md_bg_color: 0, 1, 0, .15
                radius: [10]
                ripple_behavior: False

            BoxLayout:
                size_hint: 1, 1
                pos_hint: {'center_x': .5, 'center_y': .5}
        
                AnchorLayout:

                    RecycleView:
                        id: hour_picker
                        viewclass: 'TimeScroll'
                        size_hint: None, None
                        size: dp(70), dp(120)
                        bar_width: 0
                        on_scroll_y:
                            root.check_scroll(self)

                        RecycleBoxLayout:
                            default_size: None, dp(40)
                            default_size_hint: 1, None
                            size_hint_y: None
                            height: self.minimum_height
                            orientation: 'vertical'

                AnchorLayout:

                    RecycleView:
                        id: minute_picker
                        viewclass: 'TimeScroll'
                        size_hint: None, None
                        size: dp(70), dp(120)
                        bar_width: 0
                        on_scroll_y:
                            root.check_scroll(self)

                        RecycleBoxLayout:
                            default_size: None, dp(40)
                            default_size_hint: 1, None
                            size_hint_y: None
                            height: self.minimum_height
                            orientation: 'vertical'
                
                AnchorLayout:

                    RecycleView:
                        id: ampm_picker
                        viewclass: 'TimeScroll'
                        size_hint: None, None
                        size: dp(70), dp(40)
                        bar_width: 0
                        on_scroll_y:
                            root.check_scroll(self)

                        RecycleBoxLayout:
                            default_size: None, dp(40)
                            default_size_hint: 1, None
                            size_hint_y: None
                            height: self.minimum_height
                            orientation: 'vertical'

        MDCard:
            orientation: 'horizontal'
            adaptive_height: True
            padding: [50, 0, 50, 20]

            MDCard:
                on_release:
                    root.dismiss()

                MDLabel:
                    text: "Cancel"
                    halign: "left"

            OutlinedCard:
                size_hint_x: .50
                size_hint_y: None
                height: '42dp'
                pos_hint: {'center_y': .5}
                radius: '24dp'
                md_bg_color: get_color_from_hex(Colors.BRAND_PRIMARY)
                on_release:
                    root.confirm()

                MDLabel:
                    text: "Save"
                    halign: "center"
                    theme_text_color: "Custom"
                    text_color: 1,1,1,1
