<InputDialog>
    height: '180dp'

    EnkryonOverlayCard:
        orientation: 'vertical'
        adaptive_height: True
        padding: '24dp'
        spacing: '20dp'
        radius: [16]

        MDLabel:
            text: root.title
            bold: True
            font_style: 'H6'

        FloatLayout:
            size_hint_y: None
            height: "56dp"

            MDTextField:
                id: input
                mode: "rectangle"
                text: root.text
                hint_text: ""
                size_hint_y: None
                height: "56dp"
                pos_hint:
                    {"center_x": .5, "center_y": .5}

            MDLabel:
                text: root.hint_text
                adaptive_size: True
                font_style: "Caption"
                theme_text_color: "Secondary"
                x: input.x + dp(12)
                center_y: input.top

                canvas.before:
                    Color:
                        rgba:
                            get_color_from_hex(
                            Colors.SURFACE)
                    Rectangle:
                        pos:
                            self.x - dp(4), self.y
                        size:
                            self.width + dp(8), self.height

        MDCard:
            orientation: 'horizontal'
            adaptive_height: True

            MDCard:
                on_release:
                    root.cancel()

                MDLabel:
                    text: "Cancel"
                    halign: "left"

            OutlinedCard:
                size_hint_x: .50
                size_hint_y: None
                height: '48dp'
                pos_hint: {'center_y': .5}
                radius: '24dp'
                md_bg_color: get_color_from_hex(Colors.BRAND_PRIMARY)
                on_release:
                    root.save()

                MDLabel:
                    text: "Save"
                    halign: "center"
                    theme_text_color: "Custom"
                    text_color: 1,1,1,1
