<SettingsScreen>
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: get_color_from_hex(Colors.BACKGROUND)

            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: '64dp'
            padding: '16dp', 0
            spacing: '8dp'
            canvas.before:
                Color:
                    rgba: get_color_from_hex(Colors.BRAND_PRIMARY)

                Rectangle:
                    pos: self.pos
                    size: self.size
                    
            MDIconButton:
                icon: 'arrow-left'
                on_release: root.go_to_dashboard()
                theme_icon_color: 'Custom'
                icon_color: get_color_from_hex(Colors.TEXT_ON_PRIMARY)
                pos_hint: {'center_y': .5}

            MDLabel:
                text: 'Settings'
                font_size: '26sp'
                size_hint_x: 1
                theme_text_color: 'Custom'
                text_color: get_color_from_hex(Colors.TEXT_ON_PRIMARY)

        Widget:
            size_hint_y: None
            height: "1dp"

            canvas.before:
                Color:
                    rgba: get_color_from_hex(Colors.BORDER)

                Rectangle:
                    pos: self.pos
                    size: self.size        

        ScrollView:
            size_hint_y: 1
            
            BoxLayout:
                orientation: 'vertical'
                padding: '10dp'
                spacing: '10dp'
                size_hint_y: None
                height: self.minimum_height

                OutlinedCard:
                    size_hint_y: None
                    height: '56dp'
                    padding: '10dp'
                    on_release: root.clear_data()

                    MDLabel:
                        text: 'Clear All Data'
                        theme_text_color: 'Custom'
                        text_color: get_color_from_hex(Colors.ERROR)
                        bold: True
                        valign: 'middle'
                        text_size: self.width, self.height
                        max_lines: 1
                        shorten: True
                        shorten_from: 'right'
