<TransactionCard>
    size_hint_y: None
    height: 100

    canvas.after:
        Color:
            rgba: get_color_from_hex("#1B5E20")

        Line:
            rounded_rectangle:
                (self.x, self.y,
                self.width, self.height,
                self.radius[0])
            width: 1.2

    BoxLayout:
        orientation: 'horizontal'
        padding: '10dp'

        GridLayout:
            cols: 3
            rows: 2
            size_hint_x: 0.85

            MDLabel:
                id: account_name

            MDLabel:
                id: group_name

            MDLabel:
                id: transaction_type

            MDLabel:
                id: date_time

            MDLabel:
                id: category_name

            MDLabel:
                id: amount

        GridLayout:
            cols: 2
            size_hint_x: 0.15

            MDIconButton:
                icon: 'pencil'
                on_release:
                    root.edit_transaction()

            MDIconButton:
                icon: 'delete'
                on_release:
                    root.delete_transaction()

<TransactionsScreen>
    BoxLayout:
        orientation: 'vertical'
        padding: 10

        MDCard:
            size_hint_y: None
            height: 50

            BoxLayout:
                orientation: 'horizontal'

                MDIconButton:
                    icon: 'arrow-left'
                    on_release:
                        root.go_to_dashboard()

                MDLabel:
                    text: 'Transactions'
                    halign: 'center'

        ScrollView:
            BoxLayout:
                id: transactions_container
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height