#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import Window kivy.core.window.Window

<OutlinedCard@MDCard>:
    radius: [10]
    elevation: 1

    canvas.after:
        Color:
            rgba: get_color_from_hex("#1B5E20")

        Line:
            rounded_rectangle:
                (self.x, self.y,
                self.width, self.height,
                self.radius[0])
            width: 1.2

<KeypadButton@OutlinedCard>
    ripple_behavior: True
    md_bg_color: get_color_from_hex("#FFFFFF")
    size_hint_y: None
    height: '48dp'

    AnchorLayout:
        anchor_x: "center"
        anchor_y: "center"

        MDLabel:
            id: label
            text: ""
            halign: "center"
            theme_text_color: "Custom"
            text_color: get_color_from_hex("#1B5E20")
            opacity: 1

        MDIcon:
            id: icon
            icon: ""
            theme_text_color: "Custom"
            text_color: get_color_from_hex("#1B5E20")
            opacity: 0

<AppSnackbar>:
    size_hint: None, None
    width: Window.width * 0.8
    height: "52dp"
    radius: [12]

    md_bg_color: get_color_from_hex("#1B5E20")

    elevation: 2

    opacity: 0

    MDLabel:
        id: text_label
        halign: "center"
        theme_text_color: "Custom"
        text_color: 1,1,1,1
